// GENERATED by analysis/makeBook.mjs from analysis/results/opening-book-full-alternating.json —
// do not edit by hand. The round-1 equilibrium mixtures from the exhaustive
// analysis (analysis/opening.ts, full-alternating plan space): sampled by the
// equilibrium planner when a game starts under alternating leads.

import { Order } from "./chess";

export interface BookEntry {
  p: number;
  orders: Order[];
}

export const OPENING_BOOK_ALTERNATING: { space: string; ivory: BookEntry[]; onyx: BookEntry[] } = {
  space: "full-alternating",
  ivory: [
    {
      p: 0.087912,
      orders: [
        {
          pieceId: 1,
          from: 1,
          to: 18,
          capture: false,
        },
        {
          pieceId: 11,
          from: 11,
          to: 19,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 11,
          capture: false,
        },
      ],
    },
    {
      p: 0.049451,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 18,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 10,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 3,
          capture: false,
        },
      ],
    },
    {
      p: 0.120879,
      orders: [
        {
          pieceId: 1,
          from: 1,
          to: 18,
          capture: false,
        },
        {
          pieceId: 13,
          from: 13,
          to: 29,
          capture: false,
        },
        {
          pieceId: 14,
          from: 14,
          to: 22,
          capture: false,
        },
      ],
    },
    {
      p: 0.148352,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 5,
          from: 5,
          to: 19,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 5,
          capture: false,
        },
      ],
    },
    {
      p: 0.120879,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 21,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 3,
          capture: false,
        },
      ],
    },
    {
      p: 0.06044,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 12,
          capture: false,
        },
        {
          pieceId: 14,
          from: 14,
          to: 22,
          capture: false,
        },
      ],
    },
    {
      p: 0.043956,
      orders: [
        {
          pieceId: 13,
          from: 13,
          to: 21,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 13,
          capture: false,
        },
        {
          pieceId: 4,
          from: 13,
          to: 22,
          capture: false,
        },
      ],
    },
    {
      p: 0.021978,
      orders: [
        {
          pieceId: 11,
          from: 11,
          to: 19,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 11,
          capture: false,
        },
        {
          pieceId: 4,
          from: 11,
          to: 18,
          capture: false,
        },
      ],
    },
    {
      p: 0.021978,
      orders: [
        {
          pieceId: 11,
          from: 11,
          to: 27,
          capture: false,
        },
        {
          pieceId: 13,
          from: 13,
          to: 29,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 13,
          capture: false,
        },
      ],
    },
    {
      p: 0.021978,
      orders: [
        {
          pieceId: 11,
          from: 11,
          to: 27,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 11,
          capture: false,
        },
        {
          pieceId: 4,
          from: 11,
          to: 19,
          capture: false,
        },
      ],
    },
    {
      p: 0.027473,
      orders: [
        {
          pieceId: 6,
          from: 6,
          to: 21,
          capture: false,
        },
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 12,
          capture: false,
        },
      ],
    },
    {
      p: 0.038462,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 18,
          capture: false,
        },
        {
          pieceId: 13,
          from: 13,
          to: 29,
          capture: false,
        },
        {
          pieceId: 10,
          from: 18,
          to: 27,
          capture: true,
        },
      ],
    },
    {
      p: 0.016484,
      orders: [
        {
          pieceId: 9,
          from: 9,
          to: 25,
          capture: false,
        },
        {
          pieceId: 11,
          from: 11,
          to: 19,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 11,
          capture: false,
        },
      ],
    },
    {
      p: 0.027473,
      orders: [
        {
          pieceId: 1,
          from: 1,
          to: 18,
          capture: false,
        },
        {
          pieceId: 6,
          from: 6,
          to: 21,
          capture: false,
        },
        {
          pieceId: 14,
          from: 14,
          to: 22,
          capture: false,
        },
      ],
    },
    {
      p: 0.065934,
      orders: [
        {
          pieceId: 11,
          from: 11,
          to: 27,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 11,
          capture: false,
        },
        {
          pieceId: 11,
          from: 27,
          to: 36,
          capture: true,
        },
      ],
    },
    {
      p: 0.06044,
      orders: [
        {
          pieceId: 13,
          from: 13,
          to: 29,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 13,
          capture: false,
        },
        {
          pieceId: 14,
          from: 14,
          to: 22,
          capture: false,
        },
      ],
    },
    {
      p: 0.038462,
      orders: [
        {
          pieceId: 1,
          from: 1,
          to: 18,
          capture: false,
        },
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 4,
          from: 4,
          to: 12,
          capture: false,
        },
      ],
    },
    {
      p: 0.027473,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 18,
          capture: false,
        },
        {
          pieceId: 14,
          from: 14,
          to: 22,
          capture: false,
        },
        {
          pieceId: 10,
          from: 18,
          to: 27,
          capture: true,
        },
      ],
    },
  ],
  onyx: [
    {
      p: 0.054945,
      orders: [
        {
          pieceId: 26,
          from: 50,
          to: 42,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 41,
          capture: false,
        },
        {
          pieceId: 19,
          from: 41,
          to: 13,
          capture: true,
        },
      ],
    },
    {
      p: 0.076923,
      orders: [
        {
          pieceId: 26,
          from: 50,
          to: 42,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 32,
          capture: false,
        },
        {
          pieceId: 19,
          from: 32,
          to: 11,
          capture: true,
        },
      ],
    },
    {
      p: 0.032967,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 45,
          capture: false,
        },
        {
          pieceId: 19,
          from: 45,
          to: 13,
          capture: true,
        },
      ],
    },
    {
      p: 0.021978,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 38,
          capture: false,
        },
        {
          pieceId: 19,
          from: 38,
          to: 11,
          capture: true,
        },
      ],
    },
    {
      p: 0.054945,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 31,
          capture: false,
        },
        {
          pieceId: 19,
          from: 31,
          to: 13,
          capture: true,
        },
      ],
    },
    {
      p: 0.076923,
      orders: [
        {
          pieceId: 17,
          from: 57,
          to: 42,
          capture: false,
        },
        {
          pieceId: 17,
          from: 42,
          to: 36,
          capture: false,
        },
        {
          pieceId: 17,
          from: 36,
          to: 21,
          capture: true,
        },
      ],
    },
    {
      p: 0.131868,
      orders: [
        {
          pieceId: 24,
          from: 48,
          to: 40,
          capture: false,
        },
        {
          pieceId: 22,
          from: 62,
          to: 45,
          capture: false,
        },
        {
          pieceId: 22,
          from: 45,
          to: 28,
          capture: false,
        },
      ],
    },
    {
      p: 0.021978,
      orders: [
        {
          pieceId: 25,
          from: 49,
          to: 41,
          capture: false,
        },
        {
          pieceId: 18,
          from: 58,
          to: 40,
          capture: false,
        },
        {
          pieceId: 18,
          from: 40,
          to: 12,
          capture: true,
        },
      ],
    },
    {
      p: 0.043956,
      orders: [
        {
          pieceId: 17,
          from: 57,
          to: 42,
          capture: false,
        },
        {
          pieceId: 17,
          from: 42,
          to: 27,
          capture: true,
        },
        {
          pieceId: 17,
          from: 27,
          to: 21,
          capture: true,
        },
      ],
    },
    {
      p: 0.054945,
      orders: [
        {
          pieceId: 22,
          from: 62,
          to: 47,
          capture: false,
        },
        {
          pieceId: 22,
          from: 47,
          to: 30,
          capture: false,
        },
        {
          pieceId: 22,
          from: 30,
          to: 20,
          capture: true,
        },
      ],
    },
    {
      p: 0.054945,
      orders: [
        {
          pieceId: 27,
          from: 51,
          to: 43,
          capture: false,
        },
        {
          pieceId: 18,
          from: 58,
          to: 30,
          capture: true,
        },
        {
          pieceId: 18,
          from: 30,
          to: 12,
          capture: true,
        },
      ],
    },
    {
      p: 0.076923,
      orders: [
        {
          pieceId: 22,
          from: 62,
          to: 47,
          capture: false,
        },
        {
          pieceId: 22,
          from: 47,
          to: 30,
          capture: true,
        },
        {
          pieceId: 22,
          from: 30,
          to: 20,
          capture: true,
        },
      ],
    },
    {
      p: 0.021978,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 38,
          capture: false,
        },
        {
          pieceId: 19,
          from: 38,
          to: 20,
          capture: true,
        },
      ],
    },
    {
      p: 0.010989,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 36,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 45,
          capture: false,
        },
        {
          pieceId: 19,
          from: 45,
          to: 13,
          capture: true,
        },
      ],
    },
    {
      p: 0.065934,
      orders: [
        {
          pieceId: 17,
          from: 57,
          to: 42,
          capture: false,
        },
        {
          pieceId: 17,
          from: 42,
          to: 25,
          capture: true,
        },
        {
          pieceId: 17,
          from: 25,
          to: 19,
          capture: true,
        },
      ],
    },
    {
      p: 0.021978,
      orders: [
        {
          pieceId: 22,
          from: 62,
          to: 45,
          capture: false,
        },
        {
          pieceId: 22,
          from: 45,
          to: 28,
          capture: false,
        },
        {
          pieceId: 22,
          from: 28,
          to: 18,
          capture: true,
        },
      ],
    },
    {
      p: 0.065934,
      orders: [
        {
          pieceId: 22,
          from: 62,
          to: 45,
          capture: false,
        },
        {
          pieceId: 22,
          from: 45,
          to: 28,
          capture: true,
        },
        {
          pieceId: 22,
          from: 28,
          to: 18,
          capture: true,
        },
      ],
    },
    {
      p: 0.021978,
      orders: [
        {
          pieceId: 17,
          from: 57,
          to: 42,
          capture: false,
        },
        {
          pieceId: 17,
          from: 42,
          to: 27,
          capture: true,
        },
        {
          pieceId: 17,
          from: 27,
          to: 21,
          capture: false,
        },
      ],
    },
    {
      p: 0.010989,
      orders: [
        {
          pieceId: 22,
          from: 62,
          to: 45,
          capture: false,
        },
        {
          pieceId: 22,
          from: 45,
          to: 28,
          capture: false,
        },
        {
          pieceId: 22,
          from: 28,
          to: 22,
          capture: false,
        },
      ],
    },
    {
      p: 0.010989,
      orders: [
        {
          pieceId: 22,
          from: 62,
          to: 47,
          capture: false,
        },
        {
          pieceId: 22,
          from: 47,
          to: 37,
          capture: false,
        },
        {
          pieceId: 22,
          from: 37,
          to: 22,
          capture: true,
        },
      ],
    },
    {
      p: 0.010989,
      orders: [
        {
          pieceId: 17,
          from: 57,
          to: 40,
          capture: false,
        },
        {
          pieceId: 17,
          from: 40,
          to: 34,
          capture: false,
        },
        {
          pieceId: 17,
          from: 34,
          to: 19,
          capture: false,
        },
      ],
    },
    {
      p: 0.043956,
      orders: [
        {
          pieceId: 17,
          from: 57,
          to: 40,
          capture: false,
        },
        {
          pieceId: 17,
          from: 40,
          to: 34,
          capture: false,
        },
        {
          pieceId: 17,
          from: 34,
          to: 19,
          capture: true,
        },
      ],
    },
    {
      p: 0.010989,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 31,
          capture: true,
        },
        {
          pieceId: 19,
          from: 31,
          to: 13,
          capture: true,
        },
      ],
    },
  ],
};
