// GENERATED by analysis/makeBook.mjs from analysis/results/opening-book-full.json —
// do not edit by hand. The round-1 equilibrium mixtures from the exhaustive
// analysis (analysis/opening.ts, full plan space): sampled by the
// equilibrium planner when a game starts under the standard rules.

import { Order } from "./chess";

export interface BookEntry {
  p: number;
  orders: Order[];
}

export const OPENING_BOOK: { space: string; ivory: BookEntry[]; onyx: BookEntry[] } = {
  space: "full",
  ivory: [
    {
      p: 0.011594,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 18,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 24,
          capture: false,
        },
        {
          pieceId: 3,
          from: 24,
          to: 51,
          capture: true,
        },
      ],
    },
    {
      p: 0.028986,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 21,
          capture: false,
        },
        {
          pieceId: 3,
          from: 21,
          to: 53,
          capture: true,
        },
      ],
    },
    {
      p: 0.072464,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 39,
          capture: false,
        },
        {
          pieceId: 3,
          from: 39,
          to: 53,
          capture: true,
        },
      ],
    },
    {
      p: 0.011594,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 18,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 17,
          capture: false,
        },
        {
          pieceId: 3,
          from: 17,
          to: 44,
          capture: true,
        },
      ],
    },
    {
      p: 0.057971,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 30,
          capture: false,
        },
        {
          pieceId: 3,
          from: 30,
          to: 44,
          capture: true,
        },
      ],
    },
    {
      p: 0.046377,
      orders: [
        {
          pieceId: 6,
          from: 6,
          to: 21,
          capture: false,
        },
        {
          pieceId: 6,
          from: 21,
          to: 27,
          capture: false,
        },
        {
          pieceId: 6,
          from: 27,
          to: 42,
          capture: true,
        },
      ],
    },
    {
      p: 0.075362,
      orders: [
        {
          pieceId: 6,
          from: 6,
          to: 23,
          capture: false,
        },
        {
          pieceId: 6,
          from: 23,
          to: 29,
          capture: false,
        },
        {
          pieceId: 6,
          from: 29,
          to: 44,
          capture: true,
        },
      ],
    },
    {
      p: 0.063768,
      orders: [
        {
          pieceId: 9,
          from: 9,
          to: 17,
          capture: false,
        },
        {
          pieceId: 2,
          from: 2,
          to: 16,
          capture: false,
        },
        {
          pieceId: 2,
          from: 16,
          to: 52,
          capture: true,
        },
      ],
    },
    {
      p: 0.011594,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 18,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 17,
          capture: false,
        },
        {
          pieceId: 3,
          from: 17,
          to: 35,
          capture: true,
        },
      ],
    },
    {
      p: 0.046377,
      orders: [
        {
          pieceId: 1,
          from: 1,
          to: 18,
          capture: false,
        },
        {
          pieceId: 1,
          from: 18,
          to: 35,
          capture: true,
        },
        {
          pieceId: 1,
          from: 35,
          to: 45,
          capture: true,
        },
      ],
    },
    {
      p: 0.06087,
      orders: [
        {
          pieceId: 1,
          from: 1,
          to: 18,
          capture: false,
        },
        {
          pieceId: 1,
          from: 18,
          to: 28,
          capture: false,
        },
        {
          pieceId: 1,
          from: 28,
          to: 45,
          capture: true,
        },
      ],
    },
    {
      p: 0.011594,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 18,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 10,
          capture: false,
        },
        {
          pieceId: 3,
          from: 10,
          to: 37,
          capture: true,
        },
      ],
    },
    {
      p: 0.011594,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 30,
          capture: false,
        },
        {
          pieceId: 3,
          from: 30,
          to: 54,
          capture: true,
        },
      ],
    },
    {
      p: 0.028986,
      orders: [
        {
          pieceId: 11,
          from: 11,
          to: 19,
          capture: false,
        },
        {
          pieceId: 2,
          from: 2,
          to: 38,
          capture: false,
        },
        {
          pieceId: 2,
          from: 38,
          to: 52,
          capture: true,
        },
      ],
    },
    {
      p: 0.031884,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 18,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 17,
          capture: false,
        },
        {
          pieceId: 3,
          from: 17,
          to: 53,
          capture: true,
        },
      ],
    },
    {
      p: 0.028986,
      orders: [
        {
          pieceId: 6,
          from: 6,
          to: 23,
          capture: false,
        },
        {
          pieceId: 6,
          from: 23,
          to: 29,
          capture: false,
        },
        {
          pieceId: 6,
          from: 29,
          to: 46,
          capture: true,
        },
      ],
    },
    {
      p: 0.107246,
      orders: [
        {
          pieceId: 1,
          from: 1,
          to: 16,
          capture: false,
        },
        {
          pieceId: 1,
          from: 16,
          to: 26,
          capture: false,
        },
        {
          pieceId: 1,
          from: 26,
          to: 43,
          capture: true,
        },
      ],
    },
    {
      p: 0.06087,
      orders: [
        {
          pieceId: 10,
          from: 10,
          to: 26,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 24,
          capture: false,
        },
        {
          pieceId: 3,
          from: 24,
          to: 51,
          capture: true,
        },
      ],
    },
    {
      p: 0.046377,
      orders: [
        {
          pieceId: 1,
          from: 1,
          to: 18,
          capture: false,
        },
        {
          pieceId: 1,
          from: 18,
          to: 33,
          capture: true,
        },
        {
          pieceId: 1,
          from: 33,
          to: 50,
          capture: true,
        },
      ],
    },
    {
      p: 0.002899,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 28,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 39,
          capture: false,
        },
        {
          pieceId: 3,
          from: 39,
          to: 33,
          capture: false,
        },
      ],
    },
    {
      p: 0.043478,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 28,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 30,
          capture: false,
        },
        {
          pieceId: 3,
          from: 30,
          to: 51,
          capture: true,
        },
      ],
    },
    {
      p: 0.011594,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 28,
          capture: false,
        },
        {
          pieceId: 5,
          from: 5,
          to: 33,
          capture: false,
        },
        {
          pieceId: 12,
          from: 28,
          to: 36,
          capture: false,
        },
      ],
    },
    {
      p: 0.115942,
      orders: [
        {
          pieceId: 0,
          from: 0,
          to: 1,
          capture: true,
        },
        {
          pieceId: 6,
          from: 6,
          to: 21,
          capture: false,
        },
        {
          pieceId: 6,
          from: 21,
          to: 36,
          capture: true,
        },
      ],
    },
    {
      p: 0.011594,
      orders: [
        {
          pieceId: 12,
          from: 12,
          to: 20,
          capture: false,
        },
        {
          pieceId: 3,
          from: 3,
          to: 39,
          capture: true,
        },
        {
          pieceId: 3,
          from: 39,
          to: 53,
          capture: true,
        },
      ],
    },
  ],
  onyx: [
    {
      p: 0.056522,
      orders: [
        {
          pieceId: 26,
          from: 50,
          to: 42,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 50,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 59,
          capture: false,
        },
      ],
    },
    {
      p: 0.072464,
      orders: [
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 53,
          capture: false,
        },
        {
          pieceId: 20,
          from: 53,
          to: 45,
          capture: false,
        },
      ],
    },
    {
      p: 0.010145,
      orders: [
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 53,
          capture: false,
        },
        {
          pieceId: 20,
          from: 53,
          to: 44,
          capture: true,
        },
      ],
    },
    {
      p: 0.008696,
      orders: [
        {
          pieceId: 27,
          from: 51,
          to: 35,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 35,
          capture: true,
        },
        {
          pieceId: 20,
          from: 60,
          to: 51,
          capture: true,
        },
      ],
    },
    {
      p: 0.017391,
      orders: [
        {
          pieceId: 25,
          from: 49,
          to: 33,
          capture: false,
        },
        {
          pieceId: 30,
          from: 54,
          to: 46,
          capture: false,
        },
        {
          pieceId: 28,
          from: 52,
          to: 45,
          capture: true,
        },
      ],
    },
    {
      p: 0.002899,
      orders: [
        {
          pieceId: 27,
          from: 51,
          to: 43,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 51,
          capture: false,
        },
        {
          pieceId: 20,
          from: 51,
          to: 42,
          capture: false,
        },
      ],
    },
    {
      p: 0.017391,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 52,
          capture: false,
        },
      ],
    },
    {
      p: 0.072464,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 21,
          from: 61,
          to: 43,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 61,
          capture: false,
        },
      ],
    },
    {
      p: 0.137681,
      orders: [
        {
          pieceId: 27,
          from: 51,
          to: 35,
          capture: false,
        },
        {
          pieceId: 27,
          from: 35,
          to: 28,
          capture: true,
        },
        {
          pieceId: 20,
          from: 60,
          to: 51,
          capture: true,
        },
      ],
    },
    {
      p: 0.026087,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 30,
          from: 54,
          to: 46,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 52,
          capture: false,
        },
      ],
    },
    {
      p: 0.056522,
      orders: [
        {
          pieceId: 30,
          from: 54,
          to: 46,
          capture: false,
        },
        {
          pieceId: 21,
          from: 61,
          to: 54,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 61,
          capture: false,
        },
      ],
    },
    {
      p: 0.128986,
      orders: [
        {
          pieceId: 26,
          from: 50,
          to: 42,
          capture: false,
        },
        {
          pieceId: 26,
          from: 42,
          to: 35,
          capture: true,
        },
        {
          pieceId: 20,
          from: 60,
          to: 53,
          capture: true,
        },
      ],
    },
    {
      p: 0.072464,
      orders: [
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 19,
          from: 59,
          to: 45,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 59,
          capture: false,
        },
      ],
    },
    {
      p: 0.024638,
      orders: [
        {
          pieceId: 26,
          from: 50,
          to: 42,
          capture: false,
        },
        {
          pieceId: 26,
          from: 42,
          to: 33,
          capture: true,
        },
        {
          pieceId: 20,
          from: 60,
          to: 53,
          capture: true,
        },
      ],
    },
    {
      p: 0.086957,
      orders: [
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 30,
          from: 54,
          to: 46,
          capture: false,
        },
        {
          pieceId: 26,
          from: 50,
          to: 43,
          capture: true,
        },
      ],
    },
    {
      p: 0.014493,
      orders: [
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 30,
          from: 54,
          to: 46,
          capture: false,
        },
        {
          pieceId: 28,
          from: 52,
          to: 45,
          capture: true,
        },
      ],
    },
    {
      p: 0.002899,
      orders: [
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 30,
          from: 54,
          to: 46,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 53,
          capture: true,
        },
      ],
    },
    {
      p: 0.052174,
      orders: [
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 22,
          from: 62,
          to: 45,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 53,
          capture: true,
        },
      ],
    },
    {
      p: 0.085507,
      orders: [
        {
          pieceId: 26,
          from: 50,
          to: 42,
          capture: false,
        },
        {
          pieceId: 28,
          from: 52,
          to: 44,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 52,
          capture: false,
        },
      ],
    },
    {
      p: 0.027536,
      orders: [
        {
          pieceId: 27,
          from: 51,
          to: 43,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 51,
          capture: false,
        },
        {
          pieceId: 20,
          from: 51,
          to: 42,
          capture: true,
        },
      ],
    },
    {
      p: 0.017391,
      orders: [
        {
          pieceId: 27,
          from: 51,
          to: 35,
          capture: false,
        },
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 53,
          capture: true,
        },
      ],
    },
    {
      p: 0.007246,
      orders: [
        {
          pieceId: 27,
          from: 51,
          to: 35,
          capture: false,
        },
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 51,
          capture: true,
        },
      ],
    },
    {
      p: 0.001449,
      orders: [
        {
          pieceId: 27,
          from: 51,
          to: 43,
          capture: false,
        },
        {
          pieceId: 29,
          from: 53,
          to: 37,
          capture: false,
        },
        {
          pieceId: 20,
          from: 60,
          to: 51,
          capture: true,
        },
      ],
    },
  ],
};
