import { useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import PortraitStrip from "../components/PortraitStrip";
import GrownMark from "../components/GrownMark";
import { GrowthStyle } from "../lib/growMark";
import { trackEvent } from "../lib/analytics";
import styles from "./HomePage.module.css";

// "A Field Guide to a Body of Work" — every project is a living specimen grown
// once from a seed. Four categories form one machine→hand axis; three switchable
// layouts present them. See design_handoff_portfolio_redesign/README.md.

type Layout = "guide" | "plates" | "spectrum";

interface Item {
  name: string;
  desc?: string;
  href?: string; // external link
  to?: string; // internal route
}
interface RawCategory {
  key: string;
  name: string;
  principle: string;
  accent: string;
  style: GrowthStyle;
  items: Item[];
}

const GARNISH = true; // accent buds (vs. ink-only)
const GROWTH_SEED = 1; // bump to regrow every organism
const ROMAN = ["I", "II", "III", "IV"];
const LETTERS = "abcdefgh";

// Built hand → machine, then reversed for display (machine → hand), so the
// sections read I–IV as Pure AI → AI-Enhanced → Hand-Written → Pure Creative.
const RAW: RawCategory[] = [
  {
    key: "creative",
    name: "Pure Creative Output",
    principle: "Grown entirely by hand",
    accent: "#B5482E",
    style: "wild",
    items: [
      { name: "Drawing", to: "/art" },
      { name: "Writing", to: "/writing" },
      { name: "Photography", to: "/photography" },
    ],
  },
  {
    key: "hand",
    name: "Hand-Written Code",
    principle: "Built by hand, untouched by machine",
    accent: "#5E6B36",
    style: "sapling",
    items: [
      {
        name: "clusterfun.tv",
        desc: "A Jackbox-style framework, plus the games and apps grown on top of it.",
        href: "https://clusterfun.tv",
      },
      {
        name: "hompag",
        desc: "A dynamic, editable homepage for desktop browsers.",
        href: "https://github.com/nebosite/hompag",
      },
    ],
  },
  {
    key: "hybrid",
    name: "Hand-Written, AI-Enhanced",
    principle: "Grown by hand, grafted with machine",
    accent: "#2E6E6A",
    style: "grafted",
    items: [],
  },
  {
    key: "ai",
    name: "Pure AI Output",
    principle: "Generated by machine",
    accent: "#3A5A8C",
    style: "crystal",
    items: [
      {
        name: "Pitchcraft",
        desc: "A microphone pitch-matching trainer for beginning singers.",
        to: "/pitchcraft",
      },
      {
        name: "PixelWhimsy",
        desc: "A pixel-art toy for children.",
        href: "https://pixelwhimsy.com",
      },
      {
        name: "Big Tiny Games",
        desc: "Classic games reimagined — a large canvas, original tiny pixel sprites.",
        href: "https://bigtinygames.com",
      },
      {
        name: "Budgito",
        desc: "A personal tool for working against a yearly budget.",
        href: "https://github.com/nebosite/budgito",
      },
      {
        name: "QuickNote",
        desc: "An Android app to capture an idea in two taps.",
        href: "https://github.com/nebosite/QuickNote",
      },
    ],
  },
];

interface ViewItem extends Item {
  plate: string;
  seed: string;
}
interface ViewCategory {
  key: string;
  code: string;
  name: string;
  principle: string;
  accent: string;
  style: GrowthStyle;
  emblemSeed: string;
  empty: boolean;
  items: ViewItem[];
}

function Dot({ accent, size = 7 }: { accent: string; size?: number }) {
  return (
    <span
      className={styles.dot}
      style={{
        width: size,
        height: size,
        background: GARNISH ? accent : "#1d1b16",
      }}
    />
  );
}

function ItemName({ item }: { item: ViewItem }) {
  if (item.to)
    return (
      <Link to={item.to} className={styles.itemName}>
        {item.name}
      </Link>
    );
  if (item.href)
    return (
      <a
        href={item.href}
        className={styles.itemName}
        onClick={() => trackEvent("outbound_link", { url: item.href, name: item.name })}
      >
        {item.name}
      </a>
    );
  return <span className={styles.itemName}>{item.name}</span>;
}

const TABS: Array<{ id: Layout; label: string }> = [
  { id: "guide", label: "Field Guide" },
  { id: "plates", label: "Plates" },
  { id: "spectrum", label: "Spectrum" },
];

const LAYOUT_KEY = "ej_home_layout";
const DEFAULT_LAYOUT: Layout = "spectrum";

// Remember the visitor's chosen layout across visits (defaults to Spectrum).
function initialLayout(): Layout {
  try {
    const saved = localStorage.getItem(LAYOUT_KEY);
    if (saved && TABS.some((t) => t.id === saved)) return saved as Layout;
  } catch {
    /* storage unavailable — fall back to the default */
  }
  return DEFAULT_LAYOUT;
}

export default function HomePage() {
  const [visitCount, setVisitCount] = useState<number | null>(null);
  const [layout, setLayout] = useState<Layout>(initialLayout);
  const visitRecorded = useRef(false);

  const chooseLayout = (id: Layout) => {
    setLayout(id);
    try {
      localStorage.setItem(LAYOUT_KEY, id);
    } catch {
      /* storage unavailable — choice just won't persist */
    }
  };

  useEffect(() => {
    // Guard against React StrictMode double-invoking effects in dev,
    // which would otherwise record two visits per page load.
    if (visitRecorded.current) return;
    visitRecorded.current = true;
    fetch("/api/visit", { method: "POST" })
      .then((res) => res.json())
      .then((data: { count: number }) => setVisitCount(data.count))
      .catch(() => setVisitCount(null));
  }, []);

  const categories: ViewCategory[] = useMemo(
    () =>
      [...RAW].reverse().map((c, ci) => ({
        key: c.key,
        code: ROMAN[ci],
        name: c.name,
        principle: c.principle,
        accent: c.accent,
        style: c.style,
        emblemSeed: `${c.key}-emblem`,
        empty: c.items.length === 0,
        items: c.items.map((it, ii) => ({
          ...it,
          plate: `PL. ${ROMAN[ci]}·${LETTERS[ii]}`,
          seed: `${c.key}-${it.name}`,
        })),
      })),
    [],
  );

  return (
    <div className={styles.page}>
      <div className={styles.container}>
        {/* Frontispiece — the rotating B&W portrait strip. */}
        <PortraitStrip />

        <header className={styles.header}>
          <div className={styles.headerTop}>
            <div className={styles.kicker}>A Field Guide to a Body of Work</div>
            <nav className={styles.tabs}>
              {TABS.map((t) => (
                <button
                  key={t.id}
                  type="button"
                  className={styles.tab}
                  aria-pressed={layout === t.id}
                  onClick={() => chooseLayout(t.id)}
                >
                  <span>{t.label}</span>
                  <span
                    className={styles.tabUnderline}
                    style={{
                      background: layout === t.id ? "#1d1b16" : "transparent",
                    }}
                  />
                </button>
              ))}
            </nav>
          </div>
          <h1 className={styles.name}>Eric Jorgensen</h1>
          <p className={styles.tagline}>
            Things I have made, kept as specimens and arranged in a single order — from those grown
            entirely by the hand to those generated entirely by the machine.
          </p>
        </header>

        {layout === "guide" && <GuideLayout categories={categories} />}
        {layout === "plates" && <PlatesLayout categories={categories} />}
        {layout === "spectrum" && <SpectrumLayout categories={categories} />}

        <footer className={styles.footer}>
          <span>© {new Date().getFullYear()} Eric Jorgensen</span>
          <span>Each mark grown once, never the same twice.</span>
        </footer>
      </div>

      {visitCount !== null && <p className={styles.visitCount}>{visitCount.toLocaleString()}</p>}
    </div>
  );
}

/* ---- Layout 1 · Field Guide --------------------------------------------- */
function GuideLayout({ categories }: { categories: ViewCategory[] }) {
  return (
    <main className={styles.guide}>
      {categories.map((cat) => (
        <section key={cat.key} className={styles.guideSection}>
          <div className={styles.guideLeft}>
            <div className={styles.guideCode}>{cat.code}</div>
            <div className={styles.guideEmblem}>
              <GrownMark
                seed={cat.emblemSeed}
                style={cat.style}
                accent={cat.accent}
                garnish={GARNISH}
                strokeScale={1.18}
                growthSeed={GROWTH_SEED}
              />
            </div>
          </div>
          <div className={styles.guideBody}>
            <div className={styles.principle}>
              <Dot accent={cat.accent} />
              <span>{cat.principle}</span>
            </div>
            <h2 className={styles.catName}>{cat.name}</h2>
            <div className={styles.guideItems}>
              {cat.items.map((item) => (
                <div key={item.seed} className={styles.guideItem}>
                  <div className={styles.guideItemMark}>
                    <GrownMark
                      seed={item.seed}
                      style={cat.style}
                      accent={cat.accent}
                      garnish={GARNISH}
                      strokeScale={0.85}
                      growthSeed={GROWTH_SEED}
                    />
                  </div>
                  <div className={styles.guideItemText}>
                    <h3 className={styles.guideItemH3}>
                      <ItemName item={item} />
                    </h3>
                    {item.desc && <span className={styles.itemDesc}> — {item.desc}</span>}
                  </div>
                  <div className={styles.plateLabel}>{item.plate}</div>
                </div>
              ))}
              {cat.empty && (
                <div className={styles.emptyDrawer}>
                  No specimens collected yet — this drawer is waiting.
                </div>
              )}
            </div>
          </div>
        </section>
      ))}
    </main>
  );
}

/* ---- Layout 2 · Plates --------------------------------------------------- */
function PlatesLayout({ categories }: { categories: ViewCategory[] }) {
  return (
    <main className={styles.plates}>
      {categories.map((cat) => (
        <section key={cat.key} className={styles.platesSection}>
          <div className={styles.platesBand}>
            <span className={styles.platesBandCode}>{cat.code}</span>
            <h2 className={styles.platesBandName}>{cat.name}</h2>
            <Dot accent={cat.accent} />
            <span className={styles.platesBandPrinciple}>{cat.principle}</span>
          </div>
          <div className={styles.platesGrid}>
            {cat.items.map((item) => (
              <div key={item.seed} className={styles.plate}>
                <div className={styles.platesMark}>
                  <GrownMark
                    seed={item.seed}
                    style={cat.style}
                    accent={cat.accent}
                    garnish={GARNISH}
                    strokeScale={0.85}
                    growthSeed={GROWTH_SEED}
                  />
                </div>
                <h3 className={styles.plateName}>
                  <ItemName item={item} />
                </h3>
                {item.desc && <p className={styles.plateDesc}>{item.desc}</p>}
                <div className={styles.plateFooter}>
                  <Dot accent={cat.accent} size={6} />
                  <span className={styles.plateFooterLabel}>{item.plate}</span>
                </div>
              </div>
            ))}
            {cat.empty && <div className={styles.platesEmpty}>Awaiting specimens.</div>}
          </div>
        </section>
      ))}
    </main>
  );
}

/* ---- Layout 3 · Spectrum ------------------------------------------------- */
function SpectrumLayout({ categories }: { categories: ViewCategory[] }) {
  return (
    <main className={styles.spectrum}>
      <div className={styles.spectrumEnds}>
        <span>The Machine</span>
        <span>The Hand</span>
      </div>
      <div className={styles.spectrumRule} />
      <div className={styles.spectrumGrid}>
        {categories.map((cat) => (
          <div key={cat.key} className={styles.spectrumCol}>
            <div className={styles.spectrumNode} />
            <div className={styles.spectrumEmblem}>
              <GrownMark
                seed={cat.emblemSeed}
                style={cat.style}
                accent={cat.accent}
                garnish={GARNISH}
                strokeScale={1.18}
                growthSeed={GROWTH_SEED}
              />
            </div>
            <div className={styles.spectrumCode}>{cat.code}</div>
            <h2 className={styles.spectrumName}>{cat.name}</h2>
            <div className={styles.spectrumPrinciple}>
              <Dot accent={cat.accent} />
              <span>{cat.principle}</span>
            </div>
            <div className={styles.spectrumItems}>
              {cat.items.map((item) => (
                <div key={item.seed} className={styles.spectrumItem}>
                  <div className={styles.spectrumItemMark}>
                    <GrownMark
                      seed={item.seed}
                      style={cat.style}
                      accent={cat.accent}
                      garnish={GARNISH}
                      strokeScale={0.85}
                      growthSeed={GROWTH_SEED}
                    />
                  </div>
                  <div>
                    <div className={styles.spectrumItemName}>
                      <ItemName item={item} />
                    </div>
                    {item.desc && <div className={styles.spectrumItemDesc}>{item.desc}</div>}
                  </div>
                </div>
              ))}
              {cat.empty && <div className={styles.spectrumEmpty}>Awaiting specimens.</div>}
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
