#!/usr/bin/env bash
#
# nginx-gen.sh — install nginx server blocks for all four domains. Idempotent.
#
# For each domain:
#   - If its Let's Encrypt certificate exists, install the full HTTPS config
#     from the repo's nginx/ directory.
#   - Otherwise install a generated HTTP-only bootstrap config (serves the SPA
#     and proxies /api/ on port 80). This keeps nginx valid before ssl-setup.sh
#     has run, and gives certbot's HTTP-01 challenge a server block to use.
#     Re-running this script after ssl-setup.sh upgrades every domain to HTTPS.
#
set -euo pipefail

REPO_DIR=/var/www/portfolio
SITES_AVAILABLE=/etc/nginx/sites-available
SITES_ENABLED=/etc/nginx/sites-enabled

# slug:domain:port
APPS=(
  "ericjorgensen:ericjorgensen.com:3001"
  "pixelwhimsy:pixelwhimsy.com:3002"
  "thejcrew:thejcrew.net:3003"
  "bigtinygames:bigtinygames.com:3004"
)

write_http_bootstrap_conf() {
  local slug=$1 domain=$2 port=$3 dest=$4
  cat > "${dest}" <<EOF
# HTTP-only bootstrap config for ${domain} (no SSL certificate found yet).
# Generated by nginx-gen.sh — replaced by the full HTTPS config from
# nginx/${slug}.conf after ssl-setup.sh has obtained certificates.
server {
    listen 80;
    server_name ${domain} www.${domain};

    root /var/www/portfolio/apps/${slug}/client/dist;
    index index.html;

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:${port};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}
EOF
}

for entry in "${APPS[@]}"; do
  IFS=: read -r slug domain port <<< "${entry}"
  dest="${SITES_AVAILABLE}/${slug}.conf"

  if [[ -f "/etc/letsencrypt/live/${domain}/fullchain.pem" ]]; then
    echo "==> ${domain}: certificate found — installing HTTPS config"
    cp "${REPO_DIR}/nginx/${slug}.conf" "${dest}"
  else
    echo "==> ${domain}: no certificate yet — installing HTTP-only bootstrap config"
    write_http_bootstrap_conf "${slug}" "${domain}" "${port}" "${dest}"
  fi

  ln -sf "${dest}" "${SITES_ENABLED}/${slug}.conf"
done

# Drop the distro default site so it never wins the host match
rm -f "${SITES_ENABLED}/default"

echo "==> Testing nginx config"
nginx -t

echo "==> Reloading nginx"
systemctl reload nginx

echo "==> nginx configs installed for all four domains"
