// Turn analysis/results/opening-book-<space>.json into the engine's
// src/minis/threeahead/engine/openingBook.ts.
//   node apps/ericjorgensen/client/analysis/makeBook.mjs full
//   node apps/ericjorgensen/client/analysis/makeBook.mjs full-alternating OPENING_BOOK_ALTERNATING openingBookAlternating
import fs from "node:fs";
import path from "node:path";
const here = path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/, "$1"));
const space = process.argv[2] ?? "full";
const exportName = process.argv[3] ?? "OPENING_BOOK";
const moduleName = process.argv[4] ?? "openingBook";
const book = JSON.parse(
  fs.readFileSync(path.join(here, "results", `opening-book-${space}.json`), "utf8"),
);
const round = (mix) => {
  const kept = mix.filter((e) => e.p > 1e-6);
  const total = kept.reduce((a, e) => a + e.p, 0);
  return kept.map((e) => ({ p: Number((e.p / total).toFixed(6)), orders: e.orders }));
};
const out = `// GENERATED by analysis/makeBook.mjs from analysis/results/opening-book-${space}.json —
// do not edit by hand. The round-1 equilibrium mixtures from the exhaustive
// analysis (analysis/opening.ts, ${space} plan space): sampled by the
// equilibrium planner when a game starts under ${space.endsWith("alternating") ? "alternating leads" : "the standard rules"}.

import { Order } from "./chess";

export interface BookEntry {
  p: number;
  orders: Order[];
}

export const ${exportName}: { space: string; ivory: BookEntry[]; onyx: BookEntry[] } = ${JSON.stringify(
  { space, ivory: round(book.ivory), onyx: round(book.onyx) },
  null,
  2,
)};
`;
fs.writeFileSync(
  path.join(here, "..", "src", "minis", "threeahead", "engine", `${moduleName}.ts`),
  out,
);
console.log(
  `${moduleName}.ts written from ${space}: ${book.ivory.length} Ivory / ${book.onyx.length} Onyx plans`,
);
